version: "2.1"

networks:
  test:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18080:8080"
    depends_on:
      [mongodb]
    networks:
      - test
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017